version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - nilerr
    - errorlint
    - gocritic
    - revive
    - unconvert
    - misspell
    - gosec
    - whitespace

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: unreachable-code

  exclusions:
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - path: "_test\\.go"
        linters:
          - gosec
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
